#!/bin/bash

java -jar ../../../tools/config/ConfigGenerator.jar
java -jar ../../../tools/config/ConfigGenerator.jar -help

printf "Calling the tool with invalid path option:\n"
java -jar ../../../tools/config/ConfigGenerator.jar -path=./invalid_path mlchan:mlchan "Linux Application" 1 config.rci

printf "Calling the tool with invalid option:\n"
java -jar ../../../tools/config/ConfigGenerator.jar -nooption

printf "Calling the tool with no server name specified for -server option:\n"
java -jar ../../../tools/config/ConfigGenerator.jar -server

printf "Calling the tool with -verbos=true, invalid option:\n"
java -jar ../../../tools/config/ConfigGenerator.jar -verbose=true

printf "Calling the tool with invalid vendor id:\n"
java -jar ../../../tools/config/ConfigGenerator.jar -vendor=0xLL mlchan:mlchan  "Linux Application" 1 config.rci

printf "Calling the tool with invalid firmware version number:\n"
java -jar ../../../tools/config/ConfigGenerator.jar mlchan:mlchan "Linux Application" 0x1 config.rci

printf "Calling the tool with -server= test.idigi.com:\n"
java -jar ../../../tools/config/ConfigGenerator.jar -server= test.idigi.com mlchan:mlchan "Linux Application" 1 config.rci

printf "Calling the tool with extra argument:\n"
java -jar ../../../tools/config/ConfigGenerator.jar mlchan:mlchan "Linux Application" 1 config.rci option


for file in $(ls *.rci)
do
    printf "\n\n%s\n" $file
    java -jar ../../../tools/config/ConfigGenerator.jar -server=test.idigi.com mlchan:mlchan "Linux Application" 1 $file
done
