/*
 * This is an auto-generated file - DO NOT EDIT! 
 * This is generated by ConfigGenerator tool 
 * This file was generated on: 2012/04/09 18:39:42 
 * The command line arguments were: "mlchan:***** Linux Application"1" config.rci" 
 * The version of ConfigGenerator tool was: 1.0.0.0
*/

#ifndef REMOTE_CONFIG_H
#define REMOTE_CONFIG_H

#include "idigi_remote.h"

typedef enum {
    idigi_rci_error_parser_error = 1,
    idigi_rci_error_bad_xml,
    idigi_rci_error_bad_element,
    idigi_rci_error_bad_value,
    idigi_global_error_load_fail,
    idigi_global_error_save_fail,
    idigi_global_error_memory_fail,
    idigi_global_error_COUNT,
    idigi_global_error_WIDTH = INT_MAX
}idigi_global_error_id_t;

typedef enum {
    idigi_state_debug_info_version,
    idigi_state_debug_info_stacktop,
    idigi_state_debug_info_stacksize,
    idigi_state_debug_info_stackbottom,
    idigi_state_debug_info_usedmem,
    idigi_state_debug_info_WIDTH = INT_MAX
}    idigi_state_debug_info_id_t;

typedef enum {
    idigi_setting_serial_baud_2400,
    idigi_setting_serial_baud_4800,
    idigi_setting_serial_baud_9600,
    idigi_setting_serial_baud_19200,
    idigi_setting_serial_baud_38400,
    idigi_setting_serial_baud_57600,
    idigi_setting_serial_baud_115200,
    idigi_setting_serial_baud_230400,
    idigi_setting_serial_baud_WIDTH = INT_MAX
}    idigi_setting_serial_baud_id_t;

typedef enum {
    idigi_setting_serial_parity_none,
    idigi_setting_serial_parity_odd,
    idigi_setting_serial_parity_even,
    idigi_setting_serial_parity_WIDTH = INT_MAX
}    idigi_setting_serial_parity_id_t;

typedef enum {
    idigi_setting_serial_baud,
    idigi_setting_serial_parity,
    idigi_setting_serial_databits,
    idigi_setting_serial_xbreak,
    idigi_setting_serial_txbytes,
    idigi_setting_serial_WIDTH = INT_MAX
}    idigi_setting_serial_id_t;

typedef enum {
    idigi_setting_serial_error_invalid_baud = idigi_global_error_COUNT,
    idigi_setting_serial_error_invalid_databits,
    idigi_setting_serial_error_invalid_parity,
    idigi_setting_serial_error_invalid_xbreak,
    idigi_setting_serial_error_invalid_databits_parity,
    idigi_setting_serial_error_WIDTH = INT_MAX
}    idigi_setting_serial_error_id_t;

typedef enum {
    idigi_setting_ethernet_duplex_auto,
    idigi_setting_ethernet_duplex_half,
    idigi_setting_ethernet_duplex_full,
    idigi_setting_ethernet_duplex_WIDTH = INT_MAX
}    idigi_setting_ethernet_duplex_id_t;

typedef enum {
    idigi_setting_ethernet_ip,
    idigi_setting_ethernet_subnet,
    idigi_setting_ethernet_gateway,
    idigi_setting_ethernet_dhcp,
    idigi_setting_ethernet_dns,
    idigi_setting_ethernet_duplex,
    idigi_setting_ethernet_WIDTH = INT_MAX
}    idigi_setting_ethernet_id_t;

typedef enum {
    idigi_setting_ethernet_error_invalid_duplex = idigi_global_error_COUNT,
    idigi_setting_ethernet_error_invalid_ip,
    idigi_setting_ethernet_error_invalid_subnet,
    idigi_setting_ethernet_error_invalid_gateway,
    idigi_setting_ethernet_error_invalid_dns,
    idigi_setting_ethernet_error_WIDTH = INT_MAX
}    idigi_setting_ethernet_error_id_t;

typedef enum {
    idigi_setting_device_stats_curtime,
    idigi_setting_device_stats_ctemp,
    idigi_setting_device_stats_ftemp,
    idigi_setting_device_stats_WIDTH = INT_MAX
}    idigi_setting_device_stats_id_t;

typedef enum {
    idigi_setting_device_info_product,
    idigi_setting_device_info_model,
    idigi_setting_device_info_company,
    idigi_setting_device_info_desc,
    idigi_setting_device_info_syspwd,
    idigi_setting_device_info_WIDTH = INT_MAX
}    idigi_setting_device_info_id_t;

typedef enum {
    idigi_setting_device_info_error_invalid_length = idigi_global_error_COUNT,
    idigi_setting_device_info_error_WIDTH = INT_MAX
}    idigi_setting_device_info_error_id_t;

typedef enum {
    idigi_state_debug_info,
    idigi_setting_serial,
    idigi_setting_ethernet,
    idigi_setting_device_stats,
    idigi_setting_device_info,
    idigi_setting_WIDTH = INT_MAX
}    idigi_setting_id_t;


#endif /* REMOTE_CONFIG_H */
