/*
 * This is an auto-generated file - DO NOT EDIT! 
 * This is generated by ConfigGenerator tool 
 * This file was generated on: 2012/05/08 17:30:29 
 * The command line arguments were: "-server=test.idigi.com mlchan:***** "Linux Application" 16777216 config.rci"
 * The version of ConfigGenerator tool was: 1.0.0.0 */

#ifndef remote_config_h
#define remote_config_h

#define RCI_PARSER_USES_ERROR_DESCRIPTIONS
#define RCI_PARSER_USES_UNSIGNED_INTEGER

#include "idigi_remote.h"

extern char const idigi_remote_all_strings[];

#define RCI_ENTITY_QUOTE (idigi_remote_all_strings+0)
#define RCI_ENTITY_AMPERSAND (idigi_remote_all_strings+5)
#define RCI_ENTITY_APOSTROPHE (idigi_remote_all_strings+9)
#define RCI_ENTITY_LESS_THAN (idigi_remote_all_strings+14)
#define RCI_ENTITY_GREATER_THAN (idigi_remote_all_strings+17)
#define RCI_SET_SETTING (idigi_remote_all_strings+20)
#define RCI_QUERY_SETTING (idigi_remote_all_strings+32)
#define RCI_SET_STATE (idigi_remote_all_strings+46)
#define RCI_QUERY_STATE (idigi_remote_all_strings+56)
#define RCI_VERSION (idigi_remote_all_strings+68)
#define RCI_VERSION_SUPPORTED (idigi_remote_all_strings+76)
#define RCI_REPLY (idigi_remote_all_strings+80)
#define RCI_REQUEST (idigi_remote_all_strings+90)
#define RCI_INDEX (idigi_remote_all_strings+102)
#define RCI_ID (idigi_remote_all_strings+108)
#define RCI_HINT (idigi_remote_all_strings+111)
#define RCI_ERROR (idigi_remote_all_strings+116)

typedef enum {
 idigi_rci_error_OFFSET = 1,
 idigi_rci_error_parser_error =  idigi_rci_error_OFFSET,
 idigi_rci_error_bad_xml,
 idigi_rci_error_bad_command,
 idigi_rci_error_invalid_version,
 idigi_rci_error_bad_group,
 idigi_rci_error_bad_index,
 idigi_rci_error_bad_element,
 idigi_rci_error_bad_value,
 idigi_rci_error_COUNT
} idigi_rci_error_id_t;


typedef enum {
 idigi_global_error_OFFSET = idigi_rci_error_COUNT,
 idigi_global_error_COUNT = idigi_global_error_OFFSET
} idigi_global_error_id_t;

typedef enum {
 idigi_setting_keepalive_rx,
 idigi_setting_keepalive_tx,
 idigi_setting_keepalive_COUNT
} idigi_setting_keepalive_id_t;

typedef enum {
 idigi_setting_keepalive_error_load_fail = idigi_global_error_COUNT,
 idigi_setting_keepalive_error_save_fail,
 idigi_setting_keepalive_error_no_memory,
 idigi_setting_keepalive_error_COUNT
} idigi_setting_keepalive_error_id_t;

typedef enum {
 idigi_setting_keepalive,
 idigi_setting_COUNT
} idigi_setting_id_t;



#if defined IDIGI_RCI_PARSER_INTERNAL_DATA

#define SETTING_KEEPALIVE (idigi_remote_all_strings+122)
#define SETTING_KEEPALIVE_RX (idigi_remote_all_strings+132)
#define SETTING_KEEPALIVE_TX (idigi_remote_all_strings+135)
#define SETTING_KEEPALIVE_ERROR_LOAD_FAIL (idigi_remote_all_strings+138)
#define SETTING_KEEPALIVE_ERROR_SAVE_FAIL (idigi_remote_all_strings+148)
#define SETTING_KEEPALIVE_ERROR_NO_MEMORY (idigi_remote_all_strings+158)
#define IDIGI_RCI_ERROR_PARSER_ERROR (idigi_remote_all_strings+168)
#define IDIGI_RCI_ERROR_BAD_XML (idigi_remote_all_strings+181)
#define IDIGI_RCI_ERROR_BAD_COMMAND (idigi_remote_all_strings+189)
#define IDIGI_RCI_ERROR_INVALID_VERSION (idigi_remote_all_strings+201)
#define IDIGI_RCI_ERROR_BAD_GROUP (idigi_remote_all_strings+217)
#define IDIGI_RCI_ERROR_BAD_INDEX (idigi_remote_all_strings+227)
#define IDIGI_RCI_ERROR_BAD_ELEMENT (idigi_remote_all_strings+237)
#define IDIGI_RCI_ERROR_BAD_VALUE (idigi_remote_all_strings+249)

char const idigi_remote_all_strings[] = {
 4,'q','u','o','t',
 3,'a','m','p',
 4,'a','p','o','s',
 2,'l','t',
 2,'g','t',
 11,'s','e','t','_','s','e','t','t','i','n','g',
 13,'q','u','e','r','y','_','s','e','t','t','i','n','g',
 9,'s','e','t','_','s','t','a','t','e',
 11,'q','u','e','r','y','_','s','t','a','t','e',
 7,'v','e','r','s','i','o','n',
 3,'1','.','1',
 9,'r','c','i','_','r','e','p','l','y',
 11,'r','c','i','_','r','e','q','u','e','s','t',
 5,'i','n','d','e','x',
 2,'i','d',
 4,'h','i','n','t',
 5,'e','r','r','o','r',
 9,'k','e','e','p','a','l','i','v','e',
 2,'r','x',
 2,'t','x',
 9,'l','o','a','d','_','f','a','i','l',
 9,'s','a','v','e','_','f','a','i','l',
 9,'n','o','_','m','e','m','o','r','y',
 12,'p','a','r','s','e','r','_','e','r','r','o','r',
 7,'b','a','d','_','x','m','l',
 11,'b','a','d','_','c','o','m','m','a','n','d',
 15,'i','n','v','a','l','i','d','_','v','e','r','s','i','o','n',
 9,'b','a','d','_','g','r','o','u','p',
 9,'b','a','d','_','i','n','d','e','x',
 11,'b','a','d','_','e','l','e','m','e','n','t',
 9,'b','a','d','_','v','a','l','u','e',
 '\0'
};

static idigi_element_value_unsigned_integer_t const setting_keepalive_rx_limit = {
 5,
 7200
};

static idigi_element_value_unsigned_integer_t const setting_keepalive_tx_limit = {
 5,
 7200
};

static idigi_group_element_t const setting_keepalive_elements[] = {
 { SETTING_KEEPALIVE_RX,  /*rx*/
   idigi_element_access_read_write,
   idigi_element_type_uint32,
  (idigi_element_value_limit_t *)&setting_keepalive_rx_limit
 },
 { SETTING_KEEPALIVE_TX,  /*tx*/
   idigi_element_access_read_write,
   idigi_element_type_uint32,
  (idigi_element_value_limit_t *)&setting_keepalive_tx_limit
 }
};

static char const * const setting_keepalive_errors[] = {
 SETTING_KEEPALIVE_ERROR_LOAD_FAIL, /*load_fail*/
 SETTING_KEEPALIVE_ERROR_SAVE_FAIL, /*save_fail*/
 SETTING_KEEPALIVE_ERROR_NO_MEMORY /*no_memory*/
};

static idigi_group_t const idigi_setting_groups[] = {
 { SETTING_KEEPALIVE,  /*keepalive*/
   1,
   { asizeof(setting_keepalive_elements),
     setting_keepalive_elements
   },
   { asizeof(setting_keepalive_errors),
     setting_keepalive_errors
   }
 }

};

static char const * const idigi_rci_errors[] = {
 IDIGI_RCI_ERROR_PARSER_ERROR, /*parser_error*/
 IDIGI_RCI_ERROR_BAD_XML, /*bad_xml*/
 IDIGI_RCI_ERROR_BAD_COMMAND, /*bad_command*/
 IDIGI_RCI_ERROR_INVALID_VERSION, /*invalid_version*/
 IDIGI_RCI_ERROR_BAD_GROUP, /*bad_group*/
 IDIGI_RCI_ERROR_BAD_INDEX, /*bad_index*/
 IDIGI_RCI_ERROR_BAD_ELEMENT, /*bad_element*/
 IDIGI_RCI_ERROR_BAD_VALUE /*bad_value*/
};

static idigi_group_table_t const idigi_group_table[] = {
 {idigi_setting_groups,
 asizeof(idigi_setting_groups)
 },
 {NULL,
 0
 }
};


#endif /* IDIGI_RCI_PARSER_INTERNAL_DATA */


#endif /* remote_config_h */
